services:
  db:
    image: postgres:16-alpine
    container_name: eventshuffle-db
    restart: always
    environment:
      POSTGRES_DB: eventshuffle
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d eventshuffle']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: eventshuffle-api
    build: .
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      DB_HOST: db # override for localhost
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
